server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://postgresql:5432/hoadb
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        auto-startup: true

minio:
  url: http://minio:9000
  accessKey: minioadmin
  secretKey: minioadmin

logging:
  level:
    com:
      odevo:
        hoa: INFO
    org:
      springframework: INFO
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
